package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ExampleTeamcity'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ExampleTeamcity")) {
    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "target/*.jar"

    triggers {
        add {
            vcs {
            }
        }
    }
}
